project:
  type: book
  output-dir: _book

execute:
  freeze: auto

book:
  title: Notebook
  subtitle: R for Data Science (2e)
  reader-mode: true
  sidebar:
    style: "docked"

  chapters:
    - index.qmd
    - part: "Data Visualization"
      chapters:
        - whole-game/01-data-visualization/02-first-steps.qmd
        - whole-game/01-data-visualization/04-visualizing-distributions.qmd
        - whole-game/01-data-visualization/05-visualizing-relationships.qmd
        - whole-game/01-data-visualization/06-saving-plots.qmd

    - part: "Workflow: Basics"
      chapters:
        - whole-game/02-workflow-basics/02-workflow-basics.qmd

    - part: "Data Transformation"

  appendices:
    - progress.md

format:
  html:
    callout-icon: false
    number-sections: false

render:
  - "!LICENSE"
  - "!readme.md"
