---
subtitle: Exercise Solutions
execute:
  warnings: false
  message: false
number-sections: false
---

# Themes

[Full Questions][source]

```{r libs}
#| output: false
# Loading Packages
library(tidyverse)
library(ggthemes)
```

<!-- Next Question -->
## Question 1

::: {.callout-note title='Note' collapse='false'}

### The Problem

Pick a theme offered by the ggthemes package and apply it to the last plot you made.

### The Solution

```{r}
ggplot(diamonds, aes(x = carat, y = price)) +
  geom_point(aes(color = cut), alpha = 1/20) +
  guides(color = guide_legend(override.aes = list(alpha = 1, size = 4))) +
  theme_wsj()
```

:::

<!-- Next Question -->
## Question 2

::: {.callout-note title='Note' collapse='false'}

### The Problem

Make the axis labels of your plot blue and bolded.

### The Solution

```{r}
ggplot(diamonds, aes(x = carat, y = price)) +
  geom_point(aes(color = cut), alpha = 1/20) +
  guides(color = guide_legend(override.aes = list(alpha = 1, size = 4))) + 
  theme(axis.title = element_text(color = "blue"))
```

:::

[source]: <https://r4ds.hadley.nz/communication.html#exercises-3>
