---
subtitle: Exercise Solutions
number-sections: false
---

# Workflow: Code Style

[Full Question][source]

```{r libs}
#| output: false
# Loading Packages
library(tidyverse)
library(nycflights13)
```


<!-- Next Question -->
## Question 1

::: {.callout-note title='Note' collapse='false'}

### The Problem

Restyle the following pipelines following the tidyverse guidelines.

```{r}
#| eval: false
flights|>filter(dest=="IAH")|>group_by(year,month,day)|>summarize(n=n(),
delay=mean(arr_delay,na.rm=TRUE))|>filter(n>10)

flights|>filter(carrier=="UA",dest%in%c("IAH","HOU"),sched_dep_time>
0900,sched_arr_time<2000)|>group_by(flight)|>summarize(delay=mean(
arr_delay,na.rm=TRUE),cancelled=sum(is.na(arr_delay)),n=n())|>filter(n>10)
```

### The Solution

To make the above code chunk be in the tidyverse style, most changes were to separate sections with spaces and newlines. The next most common fix was making the indents fit the style guide.
``` {r}
#| eval: false
flights |> 
    filter(dest == "IAH") |>
    group_by(year, month, day) |>
    summarize(
        n = n(),
        delay = mean(arr_delay, na.rm = TRUE)
    ) |>
    filter(n > 10)

flights |>
    filter(
        carrier == "UA",
        dest %in% c("IAH", "HOU"),
        sched_dep_time > 0900,
        sched_arr_time < 2000
    ) |>
    group_by(flight) |>
    summarize(
        delay = mean(arr_delay, na.rm=TRUE),
        cancelled = sum(is.na(arr_delay)),
        n = n()
    ) |>
    filter(n > 10)
```
:::

[source]: <https://r4ds.hadley.nz/workflow-style.html#exercises>
